server:
  port: 8085 # Gateway port
spring:
  application:
    name: API-GATEWAY-SERVICE # Gateway application name
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  security:
    user:
      name: user
      password: password

  cloud:
    gateway:
      routes:
        - id: employee-service # Unique ID for the route
          uri: http://localhost:8083 # URI of the microservice
          predicates:
            - Path=/employees/** # Route requests with path /employees/** to this service
        - id: customer-service # Another unique ID for the second route
          uri: http://localhost:8082 # URI of the second microservice
          predicates:
            - Path=/customers/** # Route requests with path /orders/** to this service

#logging:
 # level:
    #org.springframework: DEBUG
    #org.springframework.cloud.gateway: TRACE
    #org.springframework.security: DEBUG
    #org.dev.gateway.filter.RequestLoggingFilter: INFO